### ISSUE TITLE
FlexPod Select - Hasn't that been "retired"?

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/flexpod#29]
Page: [FlexPod platforms](https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_platforms.html)

TR-4036 indicates that there are 2 FlexPod Platforms: FlexPod Datacenter & FlexPod Express.  FlexPod Select was retired quite some time back and the link referenced to the Oracle configuration is dated from 2015.  This should be corrected to be in sync with the FlexPod Datacenter Technical Specifications TR (TR-4036).

**Comment by netapp-jyhshing** [comment]
@netapp-dorianh would you please update the doc to remove the FlexPod select platform?

**Comment by netapp-dorianh** [comment]
Resolved on 5-25.
