### ISSUE TITLE
Broken Links to external documentation

### ISSUE THREAD

**Issue by kecorkin** [NetAppDocs/flexpod#34]
Page: [FlexPod for Epic Directional Sizing Guide](https://docs.netapp.com/us-en/flexpod/healthcare/ehr-epic-sizing_introduction.html)

The links at the bottom of the page result in 404 errors 

TR-4693: FlexPod Datacenter for Epic EHR Deployment Guide

TR-3930i: NetApp Sizing Guidelines for Epic (requires Field Portal access)

TR-3928: NetApp Best Practices for Epic

**Comment by netapp-jyhshing** [comment]
@kaminis85 , would you please help take a look at this EPIC related issue?

**Comment by kaminis85** [comment]
Assigning this issue to Dorian Henderson
