### ISSUE TITLE
"VXLAN Multi-Site fabric for FlexPod MetroCluster IP solution" graphic missing links on Site B

### ISSUE THREAD

**Issue by bcg365** [NetAppDocs/flexpod#36]
Page: [Optional features](https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_optional_features.html)

The graphic under the heading VXLAN Multi-Site fabric for FlexPod MetroCluster IP solution, Site B, is missing the spine to leaf links from the "left" spine switch to the border GW leaf switches.

The Site A part of the graphic is correct.

**Comment by netapp-jyhshing** [comment]
I've reached out to our Cisco partner to request for the diagram update and will let Dorian know when the updated diagram is available.

**Comment by ntap-bmegan** [comment]
@netapp-jyhshing - Please update status or close if work is complete.

**Comment by ntap-bmegan** [comment]
@netapp-jyhshing - What is the status of this issue?

**Comment by netapp-jyhshing** [comment]
Cisco has updated the image to correct the missing links.

@netapp-dorianh  , would you please incorporate the changes by using updated Fig. 10 in the paper?

https://www2-realm.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/flexpod-metrocluster-ip-vxlan-multi-site-wp.pdf

Thank you!

**Comment by netapp-jyhshing** [comment]
@netapp-chandaj : This is still an issue as the image in the NetApp document described above has not been updated yet.
This is a screenshot from the Cisco document that should be used.

<img width="1263" alt="Screenshot 2023-02-02 at 10 07 02 AM" src="https://user-images.githubusercontent.com/47794273/216363258-fde39534-c42f-4ed0-bfee-914a55fcbf0d.png">

**Comment by netapp-dorianh** [comment]
I will take care of this today.
D

**Comment by netapp-dorianh** [comment]
I have replaced the offending image with the correct one here:
https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_optional_features.html#metrocluster
Please let me know if there are any other issues.

**Comment by netapp-jyhshing** [comment]
Thank you @netapp-dorianh .
