### ISSUE TITLE
Broken and incorrect links in NetApp disk shelves table

### ISSUE THREAD

**Issue by netapp-lisa** [NetAppDocs/flexpod#49]
Page: [Technical specifications and references](https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_technical_specifications_and_references.html)

Joost van Drenth emailed doccomments that the link to the tech spec for the DS460C shelf was not working. Additionally, the same "bad" link is used for the DS224C and DS212C shelves. Also, the link for the NS224 shelf goes to the repo for AFF and FAS systems, but instead needs to go to the tech spec. I believe the place all of the shelves in the table should point to is: https://www.netapp.com/data-storage/disk-shelves-storage-media/

**Comment by netapp-dorianh** [comment]
I replaced the broken links with the recommended link listed in this issue.
