### ISSUE TITLE
Update hardware and software requirements

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/flexpod#73]
### Page URL

https://docs.netapp.com/us-en/flexpod/ontap-connector-for-intersight/ci-qsg_requirements.html

### Page title

Requirements

### Summary

1. For the Component / Requirement details table, update the requirement for Virtualization Hypervisor from "vSphere 6.7 and later" to "vSphere 7.0 and later" to be consistent with the information from Cisco Intersight Help Center link below.

https://intersight.com/help/saas/supported_systems
 
2. Update the following description and link referenced below the Hardware and software requirements table to where the information can be located.

From:
"Cisco Intersight Managed Mode for FlexPod" :  https://www.cisco.com/c/en/us/solutions/collateral/data-center-virtualization/flexpod/cisco-imm-for-flexpod.html

To:
"Cisco Intersight Supported Systems": https://intersight.com/help/saas/supported_systems

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
The suggested updates have been published https://review.docs.netapp.com/us-en/flexpod_minor-fix/ontap-connector-for-intersight/ci-qsg_requirements.html
