### ISSUE TITLE
Update Cisco Intersight licensing requirements 

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/flexpod#74]
### Page URL

https://docs.netapp.com/us-en/flexpod/ontap-connector-for-intersight/ci-qsg_requirements.html

### Page title

Requirements

### Summary

The Cisco Intersight licensing requirement had changed. As a result, we need to update this section to match up with the current Cisco requirements.

1. Replace the existing description with the following from the Cisco page below.

 https://intersight.com/help/saas/getting_started/licensing_requirements/lic_infra#licensing_model
 
 
The Infrastructure Service and Cloud Orchestrator service use a subscription-based license with multiple tiers. You can choose the required Cisco UCS Server volume tier for the selected subscription term.
Licensing Model

The Cisco Intersight Infrastructure Services licensing model has been simplified and now offers the following two tiers:

    Cisco Intersight Infrastructure Services Essentials: The Essentials license tier offers server management with global health monitoring, inventory, proactive support through Cisco TAC integration, multi-factor authentication, along with SDK and API access.

    Cisco Intersight Infrastructure Services Advantage: The Advantage license tier offers advanced server management with extended visibility, ecosystem integration, and automation of Cisco and third-party hardware and software, along with multi-domain solutions.

2. Replace the information link to the udpated link.

From:
"Cisco Licensing": https://intersight.com/help/getting_started#intersight_licensing

To:
"Infrastructure Services License": https://intersight.com/help/saas/getting_started/licensing_requirements/lic_infra#licensing_model

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
The updates have been published https://docs.netapp.com/us-en/flexpod/ontap-connector-for-intersight/ci-qsg_requirements.html
