### ISSUE TITLE
Replace Cisco Intersight Managed Mode for FlexPod reference with Cisco Intersight Help Center reference

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/flexpod#75]
### Page URL

https://docs.netapp.com/us-en/flexpod/ontap-connector-for-intersight/ci-qsg_references.html

### Page title

References

### Summary

The information linked by the tag "Cisco Intersight Managed Mode for FlexPod" does not have pertinent information for Cisco Intersight.

Let us replace that reference by the "Cisco Intersight Help Center" reference below which includes all kinds of Intersight reference information.

"Cisco Intersight Help Center":   https://intersight.com/help/saas

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
The suggested updates have been published https://docs.netapp.com/us-en/flexpod/ontap-connector-for-intersight/index.html
