### ISSUE TITLE
Single volume not always best

### ISSUE THREAD

**Issue by MrObvious** [NetAppDocs/flexpod#9]
Page: [Best practices](https://docs.netapp.com/us-en/flexpod/healthcare/medical-imaging_best_practices.html)

This may require consultation with O'Mahoney or Jeff Steiner, but single LUN/Volume setups on anything more than like 4-6 CPU cores really drag with performance. Multiple volumes/LUNs are better to avoid single affinity/scsit_lu thread bottlenecks.

**Comment by DrKeno** [comment]
Is this still true with the single LUN performance improvements in ONTAP 9.9.1?

**Comment by MrObvious** [comment]
Perhaps not, but we still hit single affinity bottlenecks. Flexgroups are the obvious answer to that.

**Comment by netapp-jyhshing** [comment]
Asked Bobby to help take a look.

**Comment by ntap-bmegan** [comment]
@netapp-jyhshing - Please update status or close if work is complete.

**Comment by ntap-bmegan** [comment]
@netapp-jyhshing - What is the status of this issue?

**Comment by netapp-jyhshing** [comment]
Let me check with Bobby. Thanks.

**Comment by bobbyoommen** [comment]
Thanks for pointing this out. I am fixing it. "Place database files in a single FlexVol; don’t spread them across FlexVols". Not sure how it fell thru the crack.

Single LUN performance made significant improvement over past ONTAP releases, and could cover most of the DB use-cases in SMB, but I have seen customers running in challenges when they look for larger throughput [backups].

**Comment by bobbyoommen** [comment]
@MrObvious - The change is implemented.

**Comment by ntap-bmegan** [comment]
Can we close the issue, or is additional work required?

**Comment by bobbyoommen** [comment]
I am good closing. was waiting for @MrObvious
